name: 🆙 Bump Increment

on:
  push:
    branches:
      - main

obs:
  bump-version:
    name: 'Bump Version on master'
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout source code'
        uses: 'actions/checkout@v3'
        with:
          ref: ${{ github.ref }}
      - name: 'Automated Version Bump'
        id: version-bump
        uses: 'phips28/gh-action-bump-version@master'
        with:
          skip-tag: 'true'
          patch-wording: 'patch,fixes'
          minor-wording: 'add,Adds,new,feat'
          major-wording: 'MAJOR,cut-major'
        env:
          GITHUB_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
