name: 🆙 Bump version

on:
  push:
    branches:
      - 'main' # excludes main

jobs:
  bump-version:
    name: 'Bump Version on main'
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: 'Checkout source code'
        uses: 'actions/checkout@v3'
        with:
          ref: ${{ github.ref }}
      - name: 'Automated Version Bump'
        id: version-bump
        uses: 'phips28/gh-action-bump-version@master'
        with:
          skip-tag: 'true'
          minor-wording: 'new,feat,minor'
          major-wording: 'major'
          # commit-message: 'RELEASE: {{version}} [skip ci]'
          commit-message: 'RELEASE: {{version}}'
        env:
          GITHUB_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
